logo: ""
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

aux_links:
  "Send your photo":
    - "https://t.me/fromzero3"

aux_links_new_tab: true
footer_content: Not the official X MIPA site
